

required_pkgs <- c("tidyverse", "lme4", "lmerTest")

missing_required <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_required) > 0) {
  stop(
    "Install required package(s) before running this script: ",
    paste(missing_required, collapse = ", "),
    call. = FALSE
  )
}

library(tidyverse)
library(lme4)
library(lmerTest)

options(
  dplyr.summarise.inform = FALSE,
  readr.show_col_types = FALSE,
  contrasts = c("contr.treatment", "contr.poly")
)

set.seed(20260506)

phase2_dir <- "/Users/mahdibalotf/Desktop/project folder2/First step/phase1_phase2_outputs"
out_dir <- "/Users/mahdibalotf/Desktop/project folder2/First step/phase3_phase4_outputs"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

analytic_long_path <- file.path(phase2_dir, "hrs_phase2_analytic_long_modelready.rds")
baseline_person_path <- file.path(phase2_dir, "hrs_phase2_baseline_person.rds")

if (!file.exists(analytic_long_path)) {
  stop("Missing Phase 2 long analytic panel: ", analytic_long_path, call. = FALSE)
}

if (!file.exists(baseline_person_path)) {
  stop("Missing Phase 2 baseline person file: ", baseline_person_path, call. = FALSE)
}


id_var <- "hhidpn"
age_var <- "agey_e"
cog_var <- "cogtot27_imp"

menopause_group_levels <- c(
  "4.50-55 Natural (ref)",
  "1.Premature Natural",
  "2.Early Natural",
  "3.45-49 Natural",
  "5.Late Natural",
  "6.Surgical"
)

menopause_group_labels <- c(
  "4.50-55 Natural (ref)" = "Natural 50-55 (ref)",
  "1.Premature Natural" = "Premature natural (<40)",
  "2.Early Natural" = "Early natural (40-44)",
  "3.45-49 Natural" = "Natural 45-49",
  "5.Late Natural" = "Late natural (>55)",
  "6.Surgical" = "Surgical"
)

format_p <- function(p) {
  case_when(
    is.na(p) ~ "",
    p < 0.001 ~ "<0.001",
    TRUE ~ sprintf("%.3f", p)
  )
}

format_smd <- function(x) {
  case_when(
    is.na(x) ~ "",
    x < 0.001 ~ "<0.001",
    TRUE ~ sprintf("%.3f", x)
  )
}

format_n_pct <- function(n, denom) {
  if (is.na(denom) || denom == 0) {
    return("")
  }
  sprintf("%s (%.1f%%)", format(n, big.mark = ","), 100 * n / denom)
}

format_mean_sd <- function(x) {
  if (all(is.na(x))) {
    return("")
  }
  sprintf("%.2f (%.2f)", mean(x, na.rm = TRUE), sd(x, na.rm = TRUE))
}

format_median_iqr <- function(x) {
  if (all(is.na(x))) {
    return("")
  }
  qs <- quantile(x, probs = c(0.25, 0.5, 0.75), na.rm = TRUE, names = FALSE)
  sprintf("%.2f [%.2f, %.2f]", qs[2], qs[1], qs[3])
}

escape_html <- function(x) {
  x <- as.character(x)
  x <- replace_na(x, "")
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

write_html_table <- function(data, path, title, subtitle = NULL) {
  header <- paste0("<th>", escape_html(names(data)), "</th>", collapse = "")

  body <- purrr::map_chr(seq_len(nrow(data)), function(i) {
    cells <- paste0("<td>", escape_html(unlist(data[i, ], use.names = FALSE)), "</td>", collapse = "")
    paste0("<tr>", cells, "</tr>")
  })

  html <- c(
    "<!doctype html>",
    "<html>",
    "<head>",
    "<meta charset=\"utf-8\">",
    paste0("<title>", escape_html(title), "</title>"),
    "<style>",
    "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 28px; color: #172026; }",
    "h1 { font-size: 22px; margin-bottom: 4px; }",
    "p.subtitle { color: #52616b; margin-top: 0; max-width: 980px; line-height: 1.4; }",
    "table { border-collapse: collapse; width: 100%; font-size: 13px; }",
    "th { background: #f3f6f8; text-align: left; position: sticky; top: 0; }",
    "th, td { border: 1px solid #d9e1e7; padding: 7px 9px; vertical-align: top; }",
    "tr:nth-child(even) td { background: #fbfcfd; }",
    ".note { margin-top: 16px; color: #52616b; font-size: 12px; max-width: 980px; line-height: 1.45; }",
    "</style>",
    "</head>",
    "<body>",
    paste0("<h1>", escape_html(title), "</h1>"),
    if (!is.null(subtitle)) paste0("<p class=\"subtitle\">", escape_html(subtitle), "</p>") else NULL,
    "<table>",
    paste0("<thead><tr>", header, "</tr></thead>"),
    "<tbody>",
    body,
    "</tbody>",
    "</table>",
    "<p class=\"note\">Generated by phase3_phase4_descriptives_lmm.R. SMD values are maximum pairwise absolute SMDs across menopause groups. For categorical variables, SMDs are computed on category indicators and the covariate-level maximum is reported.</p>",
    "</body>",
    "</html>"
  )

  writeLines(html, path)
}

pairwise_groups <- function(group) {
  levs <- levels(droplevels(group))
  if (length(levs) < 2) {
    return(matrix(character(0), ncol = 2))
  }
  combn(levs, 2, simplify = TRUE)
}

continuous_pairwise_smd <- function(x, group) {
  keep <- !is.na(x) & !is.na(group)
  x <- x[keep]
  group <- droplevels(group[keep])

  pairs <- pairwise_groups(group)
  if (length(x) == 0 || ncol(pairs) == 0) {
    return(NA_real_)
  }

  smds <- purrr::map_dbl(seq_len(ncol(pairs)), function(j) {
    x1 <- x[group == pairs[1, j]]
    x2 <- x[group == pairs[2, j]]
    pooled_sd <- sqrt((var(x1, na.rm = TRUE) + var(x2, na.rm = TRUE)) / 2)

    if (is.na(pooled_sd) || pooled_sd == 0) {
      return(0)
    }

    abs((mean(x1, na.rm = TRUE) - mean(x2, na.rm = TRUE)) / pooled_sd)
  })

  max(smds, na.rm = TRUE)
}

binary_indicator_pairwise_smd <- function(indicator, group) {
  keep <- !is.na(indicator) & !is.na(group)
  indicator <- as.integer(indicator[keep])
  group <- droplevels(group[keep])

  pairs <- pairwise_groups(group)
  if (length(indicator) == 0 || ncol(pairs) == 0) {
    return(NA_real_)
  }

  smds <- purrr::map_dbl(seq_len(ncol(pairs)), function(j) {
    p1 <- mean(indicator[group == pairs[1, j]], na.rm = TRUE)
    p2 <- mean(indicator[group == pairs[2, j]], na.rm = TRUE)
    pooled_p_var <- ((p1 * (1 - p1)) + (p2 * (1 - p2))) / 2

    if (is.na(pooled_p_var) || pooled_p_var == 0) {
      return(0)
    }

    abs((p1 - p2) / sqrt(pooled_p_var))
  })

  max(smds, na.rm = TRUE)
}

categorical_level_smds <- function(x, group) {
  x <- fct_na_value_to_level(as.factor(x), level = "Missing")
  levels_x <- levels(x)

  tibble(
    level = levels_x,
    level_smd = purrr::map_dbl(levels_x, ~ binary_indicator_pairwise_smd(x == .x, group))
  )
}

anova_p_value <- function(data, variable, group_var) {
  model_data <- data %>%
    select(all_of(c(variable, group_var))) %>%
    filter(!is.na(.data[[variable]]), !is.na(.data[[group_var]]))

  if (n_distinct(model_data[[group_var]]) < 2 || nrow(model_data) == 0) {
    return(NA_real_)
  }

  fit <- lm(reformulate(group_var, response = variable), data = model_data)
  stats::anova(fit)[[5]][1]
}

chisq_p_value <- function(data, variable, group_var) {
  x <- fct_na_value_to_level(as.factor(data[[variable]]), level = "Missing")
  g <- data[[group_var]]
  tab <- table(x, g, useNA = "no")

  if (nrow(tab) < 2 || ncol(tab) < 2) {
    return(NA_real_)
  }

  suppressWarnings(stats::chisq.test(tab)$p.value)
}

summarise_continuous_for_table1 <- function(data, variable, label, group_var) {
  groups <- levels(data[[group_var]])
  group_values <- purrr::map_chr(groups, function(g) {
    format_mean_sd(data[[variable]][data[[group_var]] == g])
  })

  names(group_values) <- menopause_group_labels[groups]

  tibble(
    Characteristic = label,
    Level = "Mean (SD)",
    Overall = format_mean_sd(data[[variable]]),
    Missing = format(sum(is.na(data[[variable]])), big.mark = ","),
    `P value` = format_p(anova_p_value(data, variable, group_var)),
    `Max pairwise SMD` = format_smd(continuous_pairwise_smd(data[[variable]], data[[group_var]])),
    !!!as.list(group_values)
  ) %>%
    relocate(all_of(unname(menopause_group_labels[groups])), .after = Overall)
}

summarise_categorical_for_table1 <- function(data, variable, label, group_var) {
  groups <- levels(data[[group_var]])
  x <- fct_na_value_to_level(as.factor(data[[variable]]), level = "Missing")
  level_smds <- categorical_level_smds(x, data[[group_var]])
  covariate_smd <- max(level_smds$level_smd, na.rm = TRUE)
  p_value <- chisq_p_value(data, variable, group_var)
  n_total <- nrow(data)

  purrr::map_dfr(levels(x), function(level_i) {
    group_values <- purrr::map_chr(groups, function(g) {
      in_group <- data[[group_var]] == g
      denom <- sum(in_group, na.rm = TRUE)
      n_level <- sum(x[in_group] == level_i, na.rm = TRUE)
      format_n_pct(n_level, denom)
    })

    names(group_values) <- menopause_group_labels[groups]

    tibble(
      Characteristic = label,
      Level = as.character(level_i),
      Overall = format_n_pct(sum(x == level_i, na.rm = TRUE), n_total),
      Missing = "",
      `P value` = if_else(level_i == levels(x)[1], format_p(p_value), ""),
      `Max pairwise SMD` = if_else(level_i == levels(x)[1], format_smd(covariate_smd), ""),
      !!!as.list(group_values)
    ) %>%
      relocate(all_of(unname(menopause_group_labels[groups])), .after = Overall)
  })
}

lmer_fixed_effects_table <- function(model, model_name) {
  coefs <- as.data.frame(coef(summary(model))) %>%
    rownames_to_column("term") %>%
    as_tibble()

  p_col <- names(coefs)[str_detect(names(coefs), "^Pr\\(")]

  if (!"df" %in% names(coefs)) {
    coefs$df <- NA_real_
  }

  crit <- if_else(
    is.finite(coefs$df),
    qt(0.975, df = coefs$df),
    qnorm(0.975)
  )

  coefs %>%
    transmute(
      model = model_name,
      term = term,
      estimate = Estimate,
      std_error = `Std. Error`,
      df = df,
      conf_low = Estimate - crit * `Std. Error`,
      conf_high = Estimate + crit * `Std. Error`,
      statistic = `t value`,
      p_value = if (length(p_col) == 1) .data[[p_col]] else NA_real_
    )
}

lmer_variance_components_table <- function(model, model_name) {
  as.data.frame(VarCorr(model)) %>%
    as_tibble() %>%
    transmute(
      model = model_name,
      group = grp,
      effect_1 = var1,
      effect_2 = var2,
      variance_or_covariance = vcov,
      sd_or_correlation = sdcor
    )
}

lmer_model_diagnostics <- function(model, model_name, data) {
  convergence_messages <- model@optinfo$conv$lme4$messages
  if (is.null(convergence_messages)) {
    convergence_messages <- "None"
  }

  n_person_waves <- length(lme4::getME(model, "y"))
  model_aic <- AIC(model)
  model_bic <- BIC(model)
  model_log_likelihood <- as.numeric(logLik(model))
  model_deviance <- deviance(model)
  model_reml <- isREML(model)
  model_singular_fit <- isSingular(model, tol = 1e-4)

  tibble(
    model = model_name,
    n_person_waves = n_person_waves,
    n_persons = n_distinct(data[[id_var]]),
    aic = model_aic,
    bic = model_bic,
    log_likelihood = model_log_likelihood,
    deviance = model_deviance,
    reml = model_reml,
    singular_fit = model_singular_fit,
    convergence_messages = paste(convergence_messages, collapse = " | ")
  )
}

icc_from_random_slope_model <- function(model, model_name, age_c_values = c(-5, 0, 5, 10)) {
  vc <- as.data.frame(VarCorr(model))

  var_intercept <- vc %>%
    filter(grp == id_var, var1 == "(Intercept)", is.na(var2)) %>%
    pull(vcov)

  var_slope <- vc %>%
    filter(grp == id_var, var1 == "age_c65", is.na(var2)) %>%
    pull(vcov)

  cov_intercept_slope <- vc %>%
    filter(grp == id_var, var1 == "(Intercept)", var2 == "age_c65") %>%
    pull(vcov)

  residual_var <- vc %>%
    filter(grp == "Residual") %>%
    pull(vcov)

  if (length(var_intercept) == 0) var_intercept <- NA_real_
  if (length(var_slope) == 0) var_slope <- 0
  if (length(cov_intercept_slope) == 0) cov_intercept_slope <- 0
  if (length(residual_var) == 0) residual_var <- NA_real_

  tibble(age_c65 = age_c_values) %>%
    mutate(
      model = model_name,
      chronological_age = 65 + age_c65,
      between_person_variance =
        var_intercept +
        2 * age_c65 * cov_intercept_slope +
        (age_c65^2) * var_slope,
      residual_variance = residual_var,
      icc = between_person_variance / (between_person_variance + residual_variance),
      interpretation = if_else(
        age_c65 == 0,
        "Primary ICC at age 65 because age is centered at 65",
        "Age-specific ICC implied by random intercept-slope covariance"
      )
    ) %>%
    select(model, chronological_age, age_c65, between_person_variance, residual_variance, icc, interpretation)
}

## ---- 2. Load Phase 2 analytic files -----------------------------------------

analytic_long <- readRDS(analytic_long_path)
baseline_person <- readRDS(baseline_person_path)

if (!all(c(id_var, age_var, cog_var, "menopause_group", "baseline_wave") %in% names(analytic_long))) {
  stop("The Phase 2 long file is missing one or more variables required for Phase 3-4.", call. = FALSE)
}

## ---- 3. Analysis variable construction --------------------------------------

analysis_long <- analytic_long %>%
  mutate(
    cognitive_score = .data[[cog_var]],
    chronological_age = .data[[age_var]],
    age_c65 = chronological_age - 65,
    menopause_group = factor(menopause_group, levels = menopause_group_levels),
    menopause_group_label = factor(
      as.character(menopause_group),
      levels = menopause_group_levels,
      labels = unname(menopause_group_labels[menopause_group_levels])
    ),
    race_ethnicity = case_when(
      rahispan == 1 ~ "Hispanic",
      rahispan == 0 & raracem == 1 ~ "Non-Hispanic White",
      rahispan == 0 & raracem == 2 ~ "Non-Hispanic Black",
      rahispan == 0 & raracem == 3 ~ "Non-Hispanic Other",
      TRUE ~ "Missing/Unknown"
    ),
    race_ethnicity = factor(
      race_ethnicity,
      levels = c(
        "Non-Hispanic White",
        "Non-Hispanic Black",
        "Hispanic",
        "Non-Hispanic Other",
        "Missing/Unknown"
      )
    ),
    education_years = raedyrs,
    education_c12 = education_years - 12,
    education_category = case_when(
      raeduc == 1 ~ "Less than high school",
      raeduc == 2 ~ "GED",
      raeduc == 3 ~ "High school graduate",
      raeduc == 4 ~ "Some college",
      raeduc == 5 ~ "College or above",
      TRUE ~ "Missing"
    ),
    education_category = factor(
      education_category,
      levels = c(
        "Less than high school",
        "GED",
        "High school graduate",
        "Some college",
        "College or above",
        "Missing"
      )
    ),
    birth_year = rabyear,
    birth_year_c10 = (birth_year - 1940) / 10,
    birth_cohort_decade = paste0(floor(birth_year / 10) * 10, "s"),
    birth_cohort_decade = factor(birth_cohort_decade),
    baseline_cognitive_status = case_when(
      baseline_cogfunction == 1 ~ "Normal",
      baseline_cogfunction == 2 ~ "CIND",
      baseline_cogfunction == 3 ~ "Dementia",
      TRUE ~ "Missing"
    ),
    baseline_cognitive_status = factor(
      baseline_cognitive_status,
      levels = c("Normal", "CIND", "Dementia", "Missing")
    ),
    id_factor = factor(.data[[id_var]])
  ) %>%
  filter(
    !is.na(cognitive_score),
    !is.na(chronological_age),
    !is.na(age_c65),
    !is.na(menopause_group)
  )

baseline_analysis <- analysis_long %>%
  filter(wave == baseline_wave) %>%
  arrange(.data[[id_var]], wave) %>%
  distinct(.data[[id_var]], .keep_all = TRUE)

baseline_validation <- tibble(
  phase2_baseline_persons = nrow(baseline_person),
  phase3_baseline_rows = nrow(baseline_analysis),
  phase4_modelready_person_waves = nrow(analysis_long),
  phase4_modelready_persons = n_distinct(analysis_long[[id_var]])
)

write_csv(baseline_validation, file.path(out_dir, "phase3_phase4_input_validation.csv"))

## ---- PHASE 3A. Table 1: baseline balance diagnostics ------------------------

continuous_covariates <- tribble(
  ~variable, ~label,
  "baseline_age", "Baseline age, years",
  "baseline_cognition", "Baseline cognitive score, 0-27",
  "birth_year", "Birth year",
  "education_years", "Education, years"
)

categorical_covariates <- tribble(
  ~variable, ~label,
  "race_ethnicity", "Race/ethnicity",
  "education_category", "Education category",
  "birth_cohort_decade", "Birth cohort decade",
  "baseline_cognitive_status", "Baseline cognitive status"
)

table1_n_row <- {
  groups <- levels(baseline_analysis$menopause_group)
  group_values <- purrr::map_chr(groups, function(g) {
    format(sum(baseline_analysis$menopause_group == g, na.rm = TRUE), big.mark = ",")
  })
  names(group_values) <- menopause_group_labels[groups]

  tibble(
    Characteristic = "N",
    Level = "",
    Overall = format(nrow(baseline_analysis), big.mark = ","),
    !!!as.list(group_values),
    Missing = "",
    `P value` = "",
    `Max pairwise SMD` = ""
  )
}

table1_continuous <- purrr::pmap_dfr(
  continuous_covariates,
  ~ summarise_continuous_for_table1(
    data = baseline_analysis,
    variable = ..1,
    label = ..2,
    group_var = "menopause_group"
  )
)

table1_categorical <- purrr::pmap_dfr(
  categorical_covariates,
  ~ summarise_categorical_for_table1(
    data = baseline_analysis,
    variable = ..1,
    label = ..2,
    group_var = "menopause_group"
  )
)

table1 <- bind_rows(table1_n_row, table1_continuous, table1_categorical)

write_csv(table1, file.path(out_dir, "phase3_table1_baseline_balance.csv"))
write_html_table(
  table1,
  file.path(out_dir, "phase3_table1_baseline_balance.html"),
  title = "Table 1. Baseline Characteristics by Menopause Group",
  subtitle = "Values are mean (SD) for continuous variables and n (%) for categorical variables. P-values are one-way ANOVA or chi-squared tests. SMD is the maximum pairwise absolute standardized difference across the six menopause groups."
)

continuous_smd_diagnostics <- continuous_covariates %>%
  mutate(
    covariate_type = "continuous",
    level = NA_character_,
    max_pairwise_smd = purrr::map_dbl(
      variable,
      ~ continuous_pairwise_smd(baseline_analysis[[.x]], baseline_analysis$menopause_group)
    )
  )

categorical_smd_diagnostics <- categorical_covariates %>%
  mutate(level_smds = purrr::map(variable, ~ categorical_level_smds(
    baseline_analysis[[.x]],
    baseline_analysis$menopause_group
  ))) %>%
  select(variable, label, level_smds) %>%
  unnest(level_smds) %>%
  group_by(variable, label) %>%
  mutate(max_pairwise_smd = max(level_smd, na.rm = TRUE)) %>%
  ungroup() %>%
  transmute(
    variable,
    label,
    covariate_type = "categorical",
    level,
    level_pairwise_smd = level_smd,
    max_pairwise_smd
  )

smd_diagnostics <- bind_rows(
  continuous_smd_diagnostics %>%
    transmute(
      variable,
      label,
      covariate_type,
      level,
      level_pairwise_smd = NA_real_,
      max_pairwise_smd
    ),
  categorical_smd_diagnostics
) %>%
  arrange(desc(max_pairwise_smd), variable, desc(level_pairwise_smd))

write_csv(smd_diagnostics, file.path(out_dir, "phase3_smd_balance_diagnostics.csv"))
write_html_table(
  smd_diagnostics %>%
    mutate(
      level_pairwise_smd = format_smd(level_pairwise_smd),
      max_pairwise_smd = format_smd(max_pairwise_smd)
    ),
  file.path(out_dir, "phase3_smd_balance_diagnostics.html"),
  title = "Standardized Mean Difference Diagnostics",
  subtitle = "Rows are sorted by covariate-level maximum pairwise SMD. For categorical covariates, level_pairwise_smd identifies the category contributing to imbalance."
)

## ---- PHASE 3B. Figure 1: unadjusted LOESS trajectories ----------------------

figure1_data_summary <- analysis_long %>%
  group_by(menopause_group, menopause_group_label) %>%
  summarise(
    n_persons = n_distinct(.data[[id_var]]),
    n_person_waves = n(),
    min_age = min(chronological_age, na.rm = TRUE),
    max_age = max(chronological_age, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(figure1_data_summary, file.path(out_dir, "phase3_figure1_data_summary.csv"))

figure1 <- ggplot(
  analysis_long,
  aes(
    x = chronological_age,
    y = cognitive_score,
    color = menopause_group_label,
    fill = menopause_group_label
  )
) +
  geom_point(alpha = 0.035, size = 0.35, stroke = 0) +
  geom_smooth(
    method = "loess",
    formula = y ~ x,
    se = TRUE,
    level = 0.95,
    span = 0.75,
    linewidth = 1.05,
    alpha = 0.16
  ) +
  scale_x_continuous(
    breaks = seq(50, 105, by = 5),
    limits = c(50, max(analysis_long$chronological_age, na.rm = TRUE))
  ) +
  scale_y_continuous(
    breaks = seq(0, 27, by = 3),
    limits = c(0, 27)
  ) +
  labs(
    title = "Unadjusted Cognitive Trajectories by Menopause Group",
    subtitle = "LOESS-smoothed cognitive scores plotted against chronological age; shaded bands are 95% confidence intervals.",
    x = "Chronological age, years",
    y = "Total cognitive score, 0-27",
    color = "Menopause group",
    fill = "Menopause group"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 15),
    plot.subtitle = element_text(color = "#52616b", margin = margin(b = 10)),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

ggsave(
  filename = file.path(out_dir, "phase3_figure1_unadjusted_loess_trajectories.png"),
  plot = figure1,
  width = 11,
  height = 7.2,
  dpi = 320,
  bg = "white"
)


lmer_control <- lmerControl(
  optimizer = "bobyqa",
  optCtrl = list(maxfun = 200000),
  check.conv.singular = .makeCC(action = "message", tol = 1e-4)
)

model01_data <- analysis_long %>%
  select(
    all_of(id_var),
    id_factor,
    cognitive_score,
    age_c65,
    chronological_age,
    menopause_group
  ) %>%
  drop_na(cognitive_score, age_c65, menopause_group)

model2_data <- analysis_long %>%
  select(
    all_of(id_var),
    id_factor,
    cognitive_score,
    age_c65,
    chronological_age,
    menopause_group,
    race_ethnicity,
    birth_year,
    birth_year_c10,
    education_years,
    education_c12
  ) %>%
  drop_na(
    cognitive_score,
    age_c65,
    menopause_group,
    race_ethnicity,
    birth_year_c10,
    education_c12
  )

model_sample_diagnostics <- bind_rows(
  tibble(
    model = "Model 0 and Model 1",
    n_person_waves = nrow(model01_data),
    n_persons = n_distinct(model01_data[[id_var]]),
    exclusions_relative_to_phase2_modelready_rows = nrow(analysis_long) - nrow(model01_data),
    exclusions_relative_to_phase2_modelready_persons =
      n_distinct(analysis_long[[id_var]]) - n_distinct(model01_data[[id_var]])
  ),
  tibble(
    model = "Model 2",
    n_person_waves = nrow(model2_data),
    n_persons = n_distinct(model2_data[[id_var]]),
    exclusions_relative_to_phase2_modelready_rows = nrow(analysis_long) - nrow(model2_data),
    exclusions_relative_to_phase2_modelready_persons =
      n_distinct(analysis_long[[id_var]]) - n_distinct(model2_data[[id_var]])
  )
)

write_csv(model_sample_diagnostics, file.path(out_dir, "phase4_model_sample_diagnostics.csv"))
write_html_table(
  model_sample_diagnostics,
  file.path(out_dir, "phase4_model_sample_diagnostics.html"),
  title = "Phase 4 Model Sample Diagnostics",
  subtitle = "Model 2 uses complete cases for exogenous baseline covariates: race/ethnicity, birth year, and education years."
)


model0 <- lmerTest::lmer(
  cognitive_score ~ age_c65 + (1 + age_c65 | hhidpn),
  data = model01_data,
  REML = FALSE,
  control = lmer_control
)

# Model 1
model1 <- lmerTest::lmer(
  cognitive_score ~ menopause_group * age_c65 + (1 + age_c65 | hhidpn),
  data = model01_data,
  REML = FALSE,
  control = lmer_control
)

# Model 2
model2 <- lmerTest::lmer(
  cognitive_score ~
    menopause_group * age_c65 +
    race_ethnicity +
    birth_year_c10 +
    education_c12 +
    (1 + age_c65 | hhidpn),
  data = model2_data,
  REML = FALSE,
  control = lmer_control
)

saveRDS(model0, file.path(out_dir, "phase4_model0_unconditional_growth_lmer.rds"))
saveRDS(model1, file.path(out_dir, "phase4_model1_base_exposure_lmer.rds"))
saveRDS(model2, file.path(out_dir, "phase4_model2_exogenous_adjusted_lmer.rds"))

## ---- PHASE 4C. Extract fixed effects, variance, ICC, and fit statistics ------

fixed_effects <- bind_rows(
  lmer_fixed_effects_table(model0, "Model 0: unconditional growth"),
  lmer_fixed_effects_table(model1, "Model 1: menopause group by age"),
  lmer_fixed_effects_table(model2, "Model 2: exogenous-adjusted primary LMM")
)

fixed_effects_formatted <- fixed_effects %>%
  mutate(
    estimate = sprintf("%.4f", estimate),
    std_error = sprintf("%.4f", std_error),
    df = sprintf("%.1f", df),
    conf_low = sprintf("%.4f", conf_low),
    conf_high = sprintf("%.4f", conf_high),
    statistic = sprintf("%.3f", statistic),
    p_value = format_p(p_value)
  )

write_csv(fixed_effects, file.path(out_dir, "phase4_lmm_fixed_effects.csv"))
write_html_table(
  fixed_effects_formatted,
  file.path(out_dir, "phase4_lmm_fixed_effects.html"),
  title = "Phase 4 Linear Mixed-Effects Model Fixed Effects",
  subtitle = "Models use maximum likelihood estimation. Degrees of freedom and p-values are from lmerTest using Satterthwaite approximations."
)

variance_components <- bind_rows(
  lmer_variance_components_table(model0, "Model 0: unconditional growth"),
  lmer_variance_components_table(model1, "Model 1: menopause group by age"),
  lmer_variance_components_table(model2, "Model 2: exogenous-adjusted primary LMM")
)

variance_components_formatted <- variance_components %>%
  mutate(
    variance_or_covariance = sprintf("%.6f", variance_or_covariance),
    sd_or_correlation = sprintf("%.6f", sd_or_correlation)
  )

write_csv(variance_components, file.path(out_dir, "phase4_lmm_variance_components.csv"))
write_html_table(
  variance_components_formatted,
  file.path(out_dir, "phase4_lmm_variance_components.html"),
  title = "Phase 4 Linear Mixed-Effects Model Variance Components",
  subtitle = "Random-effects structure is person-level random intercept plus random slope for age centered at 65."
)

model_diagnostics <- bind_rows(
  lmer_model_diagnostics(model0, "Model 0: unconditional growth", model01_data),
  lmer_model_diagnostics(model1, "Model 1: menopause group by age", model01_data),
  lmer_model_diagnostics(model2, "Model 2: exogenous-adjusted primary LMM", model2_data)
)

write_csv(model_diagnostics, file.path(out_dir, "phase4_lmm_model_diagnostics.csv"))
write_html_table(
  model_diagnostics,
  file.path(out_dir, "phase4_lmm_model_diagnostics.html"),
  title = "Phase 4 Linear Mixed-Effects Model Diagnostics",
  subtitle = "Convergence messages and singular-fit flags should be reviewed before interpreting slope differences."
)

icc_model0 <- icc_from_random_slope_model(
  model0,
  "Model 0: unconditional growth",
  age_c_values = c(-10, -5, 0, 5, 10, 15)
)

write_csv(icc_model0, file.path(out_dir, "phase4_model0_icc.csv"))
write_html_table(
  icc_model0 %>%
    mutate(
      between_person_variance = sprintf("%.4f", between_person_variance),
      residual_variance = sprintf("%.4f", residual_variance),
      icc = sprintf("%.4f", icc)
    ),
  file.path(out_dir, "phase4_model0_icc.html"),
  title = "Model 0 Intraclass Correlation Coefficient",
  subtitle = "With random slopes, ICC varies by age. The primary ICC is evaluated at age 65 because age is centered there."
)





slope_difference_terms <- fixed_effects %>%
  filter(str_detect(term, "menopause_group.*:age_c65|age_c65:menopause_group")) %>%
  mutate(
    contrast = term %>%
      str_replace("menopause_group", "") %>%
      str_replace(":age_c65", "") %>%
      str_replace("age_c65:", "") %>%
      str_replace_all("`", "")
  ) %>%
  select(
    model,
    contrast,
    term,
    estimate,
    std_error,
    df,
    conf_low,
    conf_high,
    statistic,
    p_value
  )

write_csv(slope_difference_terms, file.path(out_dir, "phase4_lmm_slope_differences.csv"))
write_html_table(
  slope_difference_terms %>%
    mutate(
      estimate = sprintf("%.4f", estimate),
      std_error = sprintf("%.4f", std_error),
      df = sprintf("%.1f", df),
      conf_low = sprintf("%.4f", conf_low),
      conf_high = sprintf("%.4f", conf_high),
      statistic = sprintf("%.3f", statistic),
      p_value = format_p(p_value)
    ),
  file.path(out_dir, "phase4_lmm_slope_differences.html"),
  title = "Menopause Group Differences in Cognitive Slope",
  subtitle = "Interaction coefficients compare annual age-related cognitive change with the Natural 50-55 reference group."
)



cat("\n================ PHASE 3-4 REVIEW PACKET ================\n")

cat("\nInput validation:\n")
print(baseline_validation)

cat("\nTable 1 written to:\n")
cat(file.path(out_dir, "phase3_table1_baseline_balance.html"), "\n")
cat(file.path(out_dir, "phase3_table1_baseline_balance.csv"), "\n")

cat("\nLargest SMD diagnostics:\n")
print(
  smd_diagnostics %>%
    select(variable, label, covariate_type, level, max_pairwise_smd, level_pairwise_smd) %>%
    head(12)
)

cat("\nFigure 1 written to:\n")
cat(file.path(out_dir, "phase3_figure1_unadjusted_loess_trajectories.png"), "\n")

cat("\nModel sample diagnostics:\n")
print(model_sample_diagnostics)

cat("\nModel 0 ICC at age 65:\n")
print(icc_model0 %>% filter(age_c65 == 0))

cat("\nModel diagnostics:\n")
print(model_diagnostics)

cat("\nPrimary slope-difference terms:\n")
print(slope_difference_terms)

cat("\nAll Phase 3-4 outputs written to:\n", out_dir, "\n")
cat("Review Table 1 SMDs, Figure 1 non-linearity, and Model 2 slope differences before Phase 5.\n")


