

required_pkgs <- c("tidyverse", "lme4", "lmerTest")

missing_required <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_required) > 0) {
  stop(
    "Install required package(s) before running this script: ",
    paste(missing_required, collapse = ", "),
    call. = FALSE
  )
}

library(tidyverse)
library(lme4)
library(lmerTest)

options(
  dplyr.summarise.inform = FALSE,
  readr.show_col_types = FALSE,
  contrasts = c("contr.treatment", "contr.poly")
)

set.seed(20260507)

phase2_dir <- "/Users/mahdibalotf/Desktop/project folder2/First step/phase1_phase2_outputs"
phase4_dir <- "/Users/mahdibalotf/Desktop/project folder2/First step/phase3_phase4_outputs"
out_dir <- "/Users/mahdibalotf/Desktop/project folder2/First step/phase5_phase6_outputs"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

analytic_long_allwaves_path <- file.path(phase2_dir, "hrs_phase2_analytic_long_allwaves.rds")
analytic_long_modelready_path <- file.path(phase2_dir, "hrs_phase2_analytic_long_modelready.rds")
model2_path <- file.path(phase4_dir, "phase4_model2_exogenous_adjusted_lmer.rds")

for (path_i in c(analytic_long_allwaves_path, analytic_long_modelready_path, model2_path)) {
  if (!file.exists(path_i)) {
    stop("Required input file is missing: ", path_i, call. = FALSE)
  }
}

## ---- 1. Study constants and helper functions --------------------------------

id_var <- "hhidpn"
wave_var <- "wave"
age_var <- "agey_e"
cog_var <- "cogtot27_imp"

menopause_group_levels <- c(
  "4.50-55 Natural (ref)",
  "1.Premature Natural",
  "2.Early Natural",
  "3.45-49 Natural",
  "5.Late Natural",
  "6.Surgical"
)

natural_menopause_levels <- c(
  "4.50-55 Natural (ref)",
  "1.Premature Natural",
  "2.Early Natural",
  "3.45-49 Natural",
  "5.Late Natural"
)

menopause_group_labels <- c(
  "4.50-55 Natural (ref)" = "Natural 50-55 (ref)",
  "1.Premature Natural" = "Premature natural (<40)",
  "2.Early Natural" = "Early natural (40-44)",
  "3.45-49 Natural" = "Natural 45-49",
  "5.Late Natural" = "Late natural (>55)",
  "6.Surgical" = "Surgical"
)

format_p <- function(p) {
  case_when(
    is.na(p) ~ "",
    p < 0.001 ~ "<0.001",
    TRUE ~ sprintf("%.3f", p)
  )
}

escape_html <- function(x) {
  x <- as.character(x)
  x <- replace_na(x, "")
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

write_html_table <- function(data, path, title, subtitle = NULL) {
  header <- paste0("<th>", escape_html(names(data)), "</th>", collapse = "")

  body <- purrr::map_chr(seq_len(nrow(data)), function(i) {
    cells <- paste0("<td>", escape_html(unlist(data[i, ], use.names = FALSE)), "</td>", collapse = "")
    paste0("<tr>", cells, "</tr>")
  })

  html <- c(
    "<!doctype html>",
    "<html>",
    "<head>",
    "<meta charset=\"utf-8\">",
    paste0("<title>", escape_html(title), "</title>"),
    "<style>",
    "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 28px; color: #172026; }",
    "h1 { font-size: 22px; margin-bottom: 4px; }",
    "p.subtitle { color: #52616b; margin-top: 0; max-width: 1100px; line-height: 1.4; }",
    "table { border-collapse: collapse; width: 100%; font-size: 13px; }",
    "th { background: #f3f6f8; text-align: left; position: sticky; top: 0; }",
    "th, td { border: 1px solid #d9e1e7; padding: 7px 9px; vertical-align: top; }",
    "tr:nth-child(even) td { background: #fbfcfd; }",
    ".note { margin-top: 16px; color: #52616b; font-size: 12px; max-width: 1100px; line-height: 1.45; }",
    "</style>",
    "</head>",
    "<body>",
    paste0("<h1>", escape_html(title), "</h1>"),
    if (!is.null(subtitle)) paste0("<p class=\"subtitle\">", escape_html(subtitle), "</p>") else NULL,
    "<table>",
    paste0("<thead><tr>", header, "</tr></thead>"),
    "<tbody>",
    body,
    "</tbody>",
    "</table>",
    "<p class=\"note\">Generated by phase5_phase6_ipcw_sensitivity.R.</p>",
    "</body>",
    "</html>"
  )

  writeLines(html, path)
}

bound_probability <- function(p, eps = 1e-4) {
  pmin(pmax(p, eps), 1 - eps)
}

glm_coefficients_table <- function(model, model_name) {
  coefs <- as.data.frame(coef(summary(model))) %>%
    rownames_to_column("term") %>%
    as_tibble()

  p_col <- names(coefs)[str_detect(names(coefs), "^Pr\\(")]

  coefs %>%
    transmute(
      model = model_name,
      term = term,
      estimate = Estimate,
      std.error = `Std. Error`,
      statistic = `z value`,
      p.value = if (length(p_col) == 1) .data[[p_col]] else NA_real_
    )
}

lmer_fixed_effects_table <- function(model, model_name) {
  coefs <- as.data.frame(coef(summary(model))) %>%
    rownames_to_column("term") %>%
    as_tibble()

  p_col <- names(coefs)[str_detect(names(coefs), "^Pr\\(")]

  if (!"df" %in% names(coefs)) {
    coefs$df <- NA_real_
  }

  crit <- if_else(
    is.finite(coefs$df),
    qt(0.975, df = coefs$df),
    qnorm(0.975)
  )

  coefs %>%
    transmute(
      model = model_name,
      term = term,
      estimate = Estimate,
      std_error = `Std. Error`,
      df = df,
      conf_low = Estimate - crit * `Std. Error`,
      conf_high = Estimate + crit * `Std. Error`,
      statistic = `t value`,
      p_value = if (length(p_col) == 1) .data[[p_col]] else NA_real_
    )
}

lmer_variance_components_table <- function(model, model_name) {
  as.data.frame(VarCorr(model)) %>%
    as_tibble() %>%
    transmute(
      model = model_name,
      group = grp,
      effect_1 = var1,
      effect_2 = var2,
      variance_or_covariance = vcov,
      sd_or_correlation = sdcor
    )
}

lmer_model_diagnostics <- function(model, model_name, data, weight_var = NA_character_) {
  convergence_messages <- model@optinfo$conv$lme4$messages
  if (is.null(convergence_messages)) {
    convergence_messages <- "None"
  }

  n_person_waves <- length(lme4::getME(model, "y"))
  model_aic <- AIC(model)
  model_bic <- BIC(model)
  model_log_likelihood <- as.numeric(logLik(model))
  model_deviance <- deviance(model)
  model_reml <- isREML(model)
  model_singular_fit <- isSingular(model, tol = 1e-4)

  tibble(
    model = model_name,
    n_person_waves = n_person_waves,
    n_persons = n_distinct(data[[id_var]]),
    aic = model_aic,
    bic = model_bic,
    log_likelihood = model_log_likelihood,
    deviance = model_deviance,
    reml = model_reml,
    singular_fit = model_singular_fit,
    weights = weight_var,
    convergence_messages = paste(convergence_messages, collapse = " | ")
  )
}

format_fixed_effects <- function(data) {
  data %>%
    mutate(
      estimate = sprintf("%.4f", estimate),
      std_error = sprintf("%.4f", std_error),
      df = sprintf("%.1f", df),
      conf_low = sprintf("%.4f", conf_low),
      conf_high = sprintf("%.4f", conf_high),
      statistic = sprintf("%.3f", statistic),
      p_value = format_p(p_value)
    )
}

extract_slope_differences <- function(fixed_effects) {
  fixed_effects %>%
    filter(str_detect(term, "menopause_group.*:age_c65|age_c65:menopause_group")) %>%
    filter(!str_detect(term, "education_c12|age_c65_sq")) %>%
    mutate(
      contrast = term %>%
        str_replace("menopause_group", "") %>%
        str_replace(":age_c65", "") %>%
        str_replace("age_c65:", "") %>%
        str_replace_all("`", "")
    ) %>%
    select(
      model,
      contrast,
      term,
      estimate,
      std_error,
      df,
      conf_low,
      conf_high,
      statistic,
      p_value
    )
}

extract_three_way_interactions <- function(fixed_effects) {
  fixed_effects %>%
    filter(
      str_detect(term, "menopause_group"),
      str_detect(term, "age_c65"),
      str_detect(term, "education_c12")
    ) %>%
    mutate(
      contrast = term %>%
        str_replace("menopause_group", "") %>%
        str_replace(":age_c65", "") %>%
        str_replace(":education_c12", "") %>%
        str_replace("age_c65:", "") %>%
        str_replace("education_c12:", "") %>%
        str_replace_all("`", "")
    )
}



analytic_allwaves_raw <- readRDS(analytic_long_allwaves_path)
analytic_modelready_raw <- readRDS(analytic_long_modelready_path)
model2 <- readRDS(model2_path)



make_analysis_vars <- function(data) {
  data %>%
    mutate(
      cognitive_score = .data[[cog_var]],
      chronological_age = .data[[age_var]],
      age_c65 = chronological_age - 65,
      age_c65_sq = age_c65^2,
      menopause_group = factor(menopause_group, levels = menopause_group_levels),
      race_ethnicity = case_when(
        rahispan == 1 ~ "Hispanic",
        rahispan == 0 & raracem == 1 ~ "Non-Hispanic White",
        rahispan == 0 & raracem == 2 ~ "Non-Hispanic Black",
        rahispan == 0 & raracem == 3 ~ "Non-Hispanic Other",
        TRUE ~ "Missing/Unknown"
      ),
      race_ethnicity = factor(
        race_ethnicity,
        levels = c(
          "Non-Hispanic White",
          "Non-Hispanic Black",
          "Hispanic",
          "Non-Hispanic Other",
          "Missing/Unknown"
        )
      ),
      education_years = raedyrs,
      education_c12 = education_years - 12,
      birth_year = rabyear,
      birth_year_c10 = (birth_year - 1940) / 10,
      observed_cognition = !is.na(cognitive_score),
      id_factor = factor(.data[[id_var]])
    )
}

analysis_allwaves <- make_analysis_vars(analytic_allwaves_raw)

analysis_modelready <- make_analysis_vars(analytic_modelready_raw) %>%
  filter(
    observed_cognition,
    !is.na(age_c65),
    !is.na(menopause_group)
  )


model2_data <- analysis_modelready %>%
  drop_na(
    cognitive_score,
    age_c65,
    menopause_group,
    race_ethnicity,
    birth_year_c10,
    education_c12
  )

input_validation <- tibble(
  phase2_allwaves_rows = nrow(analysis_allwaves),
  phase2_modelready_rows = nrow(analysis_modelready),
  model2_complete_case_rows = nrow(model2_data),
  model2_complete_case_persons = n_distinct(model2_data[[id_var]])
)

write_csv(input_validation, file.path(out_dir, "phase5_phase6_input_validation.csv"))



lmer_control <- lmerControl(
  optimizer = "bobyqa",
  optCtrl = list(maxfun = 200000),
  check.conv.singular = .makeCC(action = "message", tol = 1e-4)
)

primary_lmm_formula <- cognitive_score ~
  menopause_group * age_c65 +
  race_ethnicity +
  birth_year_c10 +
  education_c12 +
  (1 + age_c65 | hhidpn)




baseline_covariates <- model2_data %>%
  filter(.data[[wave_var]] == baseline_wave) %>%
  arrange(.data[[id_var]], .data[[wave_var]]) %>%
  distinct(.data[[id_var]], .keep_all = TRUE) %>%
  transmute(
    !!id_var := .data[[id_var]],
    baseline_wave,
    menopause_group,
    race_ethnicity,
    birth_year_c10,
    education_c12,
    baseline_normal
  )

all_waves <- sort(unique(analysis_allwaves[[wave_var]]))
max_wave <- max(all_waves, na.rm = TRUE)

person_wave_grid <- baseline_covariates %>%
  select(all_of(id_var), baseline_wave) %>%
  tidyr::crossing(!!sym(wave_var) := all_waves) %>%
  filter(.data[[wave_var]] >= baseline_wave) %>%
  select(all_of(c(id_var, wave_var)))

observed_by_wave <- analysis_allwaves %>%
  semi_join(baseline_covariates, by = id_var) %>%
  group_by(.data[[id_var]], .data[[wave_var]]) %>%
  summarise(
    row_present = TRUE,
    cognitive_score = dplyr::first(cognitive_score),
    chronological_age = dplyr::first(chronological_age),
    observed_cognition = any(observed_cognition, na.rm = TRUE),
    .groups = "drop"
  )

ipcw_panel <- person_wave_grid %>%
  left_join(baseline_covariates, by = id_var) %>%
  left_join(observed_by_wave, by = c(id_var, wave_var)) %>%
  mutate(
    row_present = coalesce(row_present, FALSE),
    observed_cognition = coalesce(observed_cognition, FALSE)
  ) %>%
  arrange(.data[[id_var]], .data[[wave_var]]) %>%
  group_by(.data[[id_var]]) %>%
  mutate(
    lag_observed_cognition = lag(observed_cognition),
    lag_cognitive_score = lag(cognitive_score),
    lag_chronological_age = lag(chronological_age),
    at_risk_for_observation = .data[[wave_var]] > baseline_wave & lag_observed_cognition,
    observed_t = as.integer(observed_cognition)
  ) %>%
  ungroup()

ipcw_risk_set <- ipcw_panel %>%
  filter(at_risk_for_observation) %>%
  drop_na(
    observed_t,
    menopause_group,
    race_ethnicity,
    birth_year_c10,
    education_c12,
    lag_cognitive_score,
    lag_chronological_age
  )

denominator_formula <- observed_t ~
  menopause_group +
  race_ethnicity +
  birth_year_c10 +
  education_c12 +
  lag_cognitive_score +
  lag_chronological_age

numerator_formula <- observed_t ~
  menopause_group +
  race_ethnicity +
  birth_year_c10 +
  education_c12

ipcw_denominator_model <- glm(
  denominator_formula,
  data = ipcw_risk_set,
  family = binomial(link = "logit")
)

ipcw_numerator_model <- glm(
  numerator_formula,
  data = ipcw_risk_set,
  family = binomial(link = "logit")
)

saveRDS(
  ipcw_denominator_model,
  file.path(out_dir, "phase5_ipcw_denominator_model.rds")
)

saveRDS(
  ipcw_numerator_model,
  file.path(out_dir, "phase5_ipcw_numerator_model.rds")
)

ipcw_glm_coefficients <- bind_rows(
  glm_coefficients_table(
    ipcw_denominator_model,
    "Denominator: baseline covariates + lagged cognition + lagged age"
  ),
  glm_coefficients_table(
    ipcw_numerator_model,
    "Numerator: baseline covariates only"
  )
)

write_csv(ipcw_glm_coefficients, file.path(out_dir, "phase5_ipcw_glm_coefficients.csv"))
write_html_table(
  ipcw_glm_coefficients %>%
    mutate(
      estimate = sprintf("%.4f", estimate),
      std.error = sprintf("%.4f", std.error),
      statistic = sprintf("%.3f", statistic),
      p.value = format_p(p.value)
    ),
  file.path(out_dir, "phase5_ipcw_glm_coefficients.html"),
  title = "IPCW Observation Models",
  subtitle = "Logistic models estimate the probability of being observed at wave t conditional on valid cognition at wave t-1."
)

ipcw_predictions <- ipcw_risk_set %>%
  mutate(
    p_observed_denominator = bound_probability(
      predict(ipcw_denominator_model, newdata = ipcw_risk_set, type = "response")
    ),
    p_observed_numerator = bound_probability(
      predict(ipcw_numerator_model, newdata = ipcw_risk_set, type = "response")
    ),
    stabilized_transition_weight = p_observed_numerator / p_observed_denominator
  ) %>%
  select(
    all_of(c(id_var, wave_var)),
    p_observed_denominator,
    p_observed_numerator,
    stabilized_transition_weight
  )

ipcw_weights_by_wave <- ipcw_panel %>%
  left_join(ipcw_predictions, by = c(id_var, wave_var)) %>%
  mutate(
    transition_weight_for_observed_outcome = case_when(
      at_risk_for_observation & observed_cognition ~ stabilized_transition_weight,
      TRUE ~ 1
    ),
    transition_weight_for_observed_outcome = replace_na(transition_weight_for_observed_outcome, 1)
  ) %>%
  arrange(.data[[id_var]], .data[[wave_var]]) %>%
  group_by(.data[[id_var]]) %>%
  mutate(sw_cumulative = cumprod(transition_weight_for_observed_outcome)) %>%
  ungroup()

model4_data_untruncated <- model2_data %>%
  left_join(
    ipcw_weights_by_wave %>%
      select(all_of(c(id_var, wave_var)), sw_cumulative),
    by = c(id_var, wave_var)
  ) %>%
  mutate(sw_cumulative = replace_na(sw_cumulative, 1))

weight_bounds <- quantile(
  model4_data_untruncated$sw_cumulative,
  probs = c(0.01, 0.99),
  na.rm = TRUE,
  names = FALSE
)

model4_data <- model4_data_untruncated %>%
  mutate(
    sw_truncated = pmin(pmax(sw_cumulative, weight_bounds[1]), weight_bounds[2])
  )

ipcw_weight_summary <- model4_data %>%
  summarise(
    n_person_waves = n(),
    n_persons = n_distinct(.data[[id_var]]),
    risk_set_rows_for_ipcw_models = nrow(ipcw_risk_set),
    observed_probability_mean_denominator =
      mean(ipcw_predictions$p_observed_denominator, na.rm = TRUE),
    observed_probability_mean_numerator =
      mean(ipcw_predictions$p_observed_numerator, na.rm = TRUE),
    sw_untruncated_min = min(sw_cumulative, na.rm = TRUE),
    sw_untruncated_p01 = quantile(sw_cumulative, 0.01, na.rm = TRUE),
    sw_untruncated_mean = mean(sw_cumulative, na.rm = TRUE),
    sw_untruncated_median = median(sw_cumulative, na.rm = TRUE),
    sw_untruncated_p99 = quantile(sw_cumulative, 0.99, na.rm = TRUE),
    sw_untruncated_max = max(sw_cumulative, na.rm = TRUE),
    sw_truncated_min = min(sw_truncated, na.rm = TRUE),
    sw_truncated_mean = mean(sw_truncated, na.rm = TRUE),
    sw_truncated_median = median(sw_truncated, na.rm = TRUE),
    sw_truncated_max = max(sw_truncated, na.rm = TRUE)
  )

write_csv(ipcw_weight_summary, file.path(out_dir, "phase5_ipcw_weight_summary.csv"))
write_html_table(
  ipcw_weight_summary %>%
    mutate(across(where(is.numeric), ~ sprintf("%.4f", .x))),
  file.path(out_dir, "phase5_ipcw_weight_summary.html"),
  title = "IPCW Stabilized Weight Diagnostics",
  subtitle = "Cumulative stabilized weights are truncated at the 1st and 99th percentiles among Model 2 complete-case person-waves."
)

write_csv(
  model4_data %>%
    select(all_of(c(id_var, wave_var)), sw_cumulative, sw_truncated),
  file.path(out_dir, "phase5_ipcw_weights_by_observed_person_wave.csv")
)



model3 <- lmerTest::lmer(
  cognitive_score ~
    menopause_group * age_c65 * education_c12 +
    race_ethnicity +
    birth_year_c10 +
    (1 + age_c65 | hhidpn),
  data = model2_data,
  REML = FALSE,
  control = lmer_control
)

model4 <- lmerTest::lmer(
  primary_lmm_formula,
  data = model4_data,
  weights = sw_truncated,
  REML = FALSE,
  control = lmer_control
)

saveRDS(model3, file.path(out_dir, "phase5_model3_cognitive_reserve_lmer.rds"))
saveRDS(model4, file.path(out_dir, "phase5_model4_ipcw_weighted_lmer.rds"))



model5 <- lmerTest::lmer(
  cognitive_score ~
    menopause_group * age_c65 +
    menopause_group * age_c65_sq +
    race_ethnicity +
    birth_year_c10 +
    education_c12 +
    (1 + age_c65 | hhidpn),
  data = model2_data,
  REML = FALSE,
  control = lmer_control
)

model6_data <- model2_data %>%
  filter(baseline_normal == 1)

model6 <- lmerTest::lmer(
  primary_lmm_formula,
  data = model6_data,
  REML = FALSE,
  control = lmer_control
)

model7_data <- model2_data %>%
  filter(menopause_group %in% natural_menopause_levels) %>%
  mutate(menopause_group = factor(as.character(menopause_group), levels = natural_menopause_levels))

model7 <- lmerTest::lmer(
  primary_lmm_formula,
  data = model7_data,
  REML = FALSE,
  control = lmer_control
)

saveRDS(model5, file.path(out_dir, "phase6_model5_quadratic_age_lmer.rds"))
saveRDS(model6, file.path(out_dir, "phase6_model6_baseline_normal_only_lmer.rds"))
saveRDS(model7, file.path(out_dir, "phase6_model7_natural_menopause_only_lmer.rds"))

## ---- PHASE 5-6B. Extract model results --------------------------------------

fixed_effects_all <- bind_rows(
  lmer_fixed_effects_table(model2, "Model 2: primary unweighted adjusted LMM"),
  lmer_fixed_effects_table(model3, "Model 3: cognitive reserve interaction"),
  lmer_fixed_effects_table(model4, "Model 4: IPCW-weighted adjusted LMM"),
  lmer_fixed_effects_table(model5, "Model 5: quadratic age adjusted LMM"),
  lmer_fixed_effects_table(model6, "Model 6: baseline-normal-only adjusted LMM"),
  lmer_fixed_effects_table(model7, "Model 7: natural-menopause-only adjusted LMM")
)

write_csv(fixed_effects_all, file.path(out_dir, "phase5_phase6_lmm_fixed_effects.csv"))
write_html_table(
  format_fixed_effects(fixed_effects_all),
  file.path(out_dir, "phase5_phase6_lmm_fixed_effects.html"),
  title = "Phase 5-6 Linear Mixed-Effects Model Fixed Effects",
  subtitle = "All LMMs use maximum likelihood estimation and person-level random intercepts plus random slopes for age centered at 65."
)

variance_components_all <- bind_rows(
  lmer_variance_components_table(model3, "Model 3: cognitive reserve interaction"),
  lmer_variance_components_table(model4, "Model 4: IPCW-weighted adjusted LMM"),
  lmer_variance_components_table(model5, "Model 5: quadratic age adjusted LMM"),
  lmer_variance_components_table(model6, "Model 6: baseline-normal-only adjusted LMM"),
  lmer_variance_components_table(model7, "Model 7: natural-menopause-only adjusted LMM")
)

write_csv(variance_components_all, file.path(out_dir, "phase5_phase6_lmm_variance_components.csv"))
write_html_table(
  variance_components_all %>%
    mutate(
      variance_or_covariance = sprintf("%.6f", variance_or_covariance),
      sd_or_correlation = sprintf("%.6f", sd_or_correlation)
    ),
  file.path(out_dir, "phase5_phase6_lmm_variance_components.html"),
  title = "Phase 5-6 Linear Mixed-Effects Model Variance Components",
  subtitle = "Random-effects structure is person-level random intercept plus random slope for age centered at 65."
)

model_diagnostics_all <- bind_rows(
  lmer_model_diagnostics(model2, "Model 2: primary unweighted adjusted LMM", model2_data),
  lmer_model_diagnostics(model3, "Model 3: cognitive reserve interaction", model2_data),
  lmer_model_diagnostics(model4, "Model 4: IPCW-weighted adjusted LMM", model4_data, "sw_truncated"),
  lmer_model_diagnostics(model5, "Model 5: quadratic age adjusted LMM", model2_data),
  lmer_model_diagnostics(model6, "Model 6: baseline-normal-only adjusted LMM", model6_data),
  lmer_model_diagnostics(model7, "Model 7: natural-menopause-only adjusted LMM", model7_data)
)

write_csv(model_diagnostics_all, file.path(out_dir, "phase5_phase6_lmm_model_diagnostics.csv"))
write_html_table(
  model_diagnostics_all,
  file.path(out_dir, "phase5_phase6_lmm_model_diagnostics.html"),
  title = "Phase 5-6 Model Diagnostics",
  subtitle = "Review convergence messages and singular-fit flags before interpreting robustness patterns."
)



model3_three_way_interactions <- fixed_effects_all %>%
  filter(model == "Model 3: cognitive reserve interaction") %>%
  extract_three_way_interactions() %>%
  select(
    model,
    contrast,
    term,
    estimate,
    std_error,
    df,
    conf_low,
    conf_high,
    statistic,
    p_value
  )

write_csv(
  model3_three_way_interactions,
  file.path(out_dir, "phase5_model3_cognitive_reserve_three_way_interactions.csv")
)

write_html_table(
  format_fixed_effects(model3_three_way_interactions),
  file.path(out_dir, "phase5_model3_cognitive_reserve_three_way_interactions.html"),
  title = "Model 3 Cognitive Reserve Three-Way Interactions",
  subtitle = "Terms test whether education modifies menopause-group differences in age-related cognitive slopes."
)



nonlinear_model_comparison <- model_diagnostics_all %>%
  filter(model %in% c(
    "Model 2: primary unweighted adjusted LMM",
    "Model 5: quadratic age adjusted LMM"
  )) %>%
  select(model, n_person_waves, n_persons, aic, bic, log_likelihood, deviance, singular_fit, convergence_messages) %>%
  arrange(aic) %>%
  mutate(
    delta_aic_vs_best = aic - min(aic, na.rm = TRUE),
    delta_bic_vs_best = bic - min(bic, na.rm = TRUE)
  )

write_csv(nonlinear_model_comparison, file.path(out_dir, "phase6_model5_nonlinear_model_comparison.csv"))
write_html_table(
  nonlinear_model_comparison %>%
    mutate(
      aic = sprintf("%.2f", aic),
      bic = sprintf("%.2f", bic),
      log_likelihood = sprintf("%.2f", log_likelihood),
      deviance = sprintf("%.2f", deviance),
      delta_aic_vs_best = sprintf("%.2f", delta_aic_vs_best),
      delta_bic_vs_best = sprintf("%.2f", delta_bic_vs_best)
    ),
  file.path(out_dir, "phase6_model5_nonlinear_model_comparison.html"),
  title = "Linear vs Quadratic Aging Model Comparison",
  subtitle = "Model 5 adds age_c65^2 and menopause group x age_c65^2 terms to the primary adjusted LMM."
)



sensitivity_slope_summary <- bind_rows(
  fixed_effects_all %>%
    filter(model == "Model 2: primary unweighted adjusted LMM") %>%
    extract_slope_differences(),
  fixed_effects_all %>%
    filter(model == "Model 4: IPCW-weighted adjusted LMM") %>%
    extract_slope_differences(),
  fixed_effects_all %>%
    filter(model == "Model 6: baseline-normal-only adjusted LMM") %>%
    extract_slope_differences(),
  fixed_effects_all %>%
    filter(model == "Model 7: natural-menopause-only adjusted LMM") %>%
    extract_slope_differences()
) %>%
  mutate(
    contrast_label = recode(contrast, !!!menopause_group_labels),
    estimate_ci = sprintf("%.4f [%.4f, %.4f]", estimate, conf_low, conf_high),
    p_value_formatted = format_p(p_value)
  ) %>%
  select(
    model,
    contrast = contrast_label,
    estimate,
    std_error,
    conf_low,
    conf_high,
    p_value,
    estimate_ci,
    p_value_formatted,
    term
  ) %>%
  arrange(contrast, model)

sensitivity_slope_summary_wide <- sensitivity_slope_summary %>%
  select(model, contrast, estimate_ci, p_value_formatted) %>%
  mutate(result = paste0(estimate_ci, "; p=", p_value_formatted)) %>%
  select(model, contrast, result) %>%
  pivot_wider(names_from = model, values_from = result) %>%
  arrange(contrast)

write_csv(
  sensitivity_slope_summary,
  file.path(out_dir, "phase5_phase6_sensitivity_slope_summary_long.csv")
)

write_csv(
  sensitivity_slope_summary_wide,
  file.path(out_dir, "phase5_phase6_sensitivity_summary_table.csv")
)

write_html_table(
  sensitivity_slope_summary_wide,
  file.path(out_dir, "phase5_phase6_sensitivity_summary_table.html"),
  title = "Sensitivity Summary Table: Menopause Group Differences in Cognitive Slope",
  subtitle = "Entries are menopause x age_c65 interaction estimates with 95% CIs and p-values. The reference group is natural menopause at ages 50-55. Model 7 excludes surgical menopause, so the surgical contrast is intentionally absent."
)

## ---- 7. Console review packet ------------------------------------------------

cat("\n================ PHASE 5-6 REVIEW PACKET ================\n")

cat("\nInput validation:\n")
print(input_validation)

cat("\nIPCW weight summary:\n")
print(ipcw_weight_summary)

cat("\nModel diagnostics:\n")
print(model_diagnostics_all)

cat("\nModel 3 cognitive reserve three-way interaction terms:\n")
print(model3_three_way_interactions)

cat("\nLinear vs quadratic age comparison:\n")
print(nonlinear_model_comparison)

cat("\nSensitivity slope summary:\n")
print(sensitivity_slope_summary)

cat("\nPrimary outputs written to:\n")
cat(file.path(out_dir, "phase5_phase6_lmm_fixed_effects.html"), "\n")
cat(file.path(out_dir, "phase5_model3_cognitive_reserve_three_way_interactions.html"), "\n")
cat(file.path(out_dir, "phase6_model5_nonlinear_model_comparison.html"), "\n")
cat(file.path(out_dir, "phase5_phase6_sensitivity_summary_table.html"), "\n")

cat("\nAll Phase 5-6 outputs written to:\n", out_dir, "\n")


